### ISSUE TITLE
ostype is ignored when regex is given

### ISSUE THREAD

**Issue by LarsKollstedt** [ytti/oxidized-script#25]
Hi ytti,

I tried to combine the options --regex and --ostype, this leads to the ostype beeing ignored, which might be even dangerous in some corner case scenarios.
I found nothing about this in your documentation and would prefer oxidized_script to support this combinations. I made Pull-Request #21 for this, last year.

And now the issue in hope to clarify and remind. ;-) Please have a look at it on occassion. I'm using this patched version for almost a year, now.

Kind regards,
       Lars

**Comment by ytti** [comment]
Thanks for pinging me. I'm not paying super close attention to these. The is starting to look quite wet after that PR, I try to find time to think about how to refactor it to be bit more dry.

**Comment by LarsKollstedt** [comment]
Hi ytti,

I tried to consolidate this a bit in my branch filter_thoughts. This are just thoughts at this moment, and I'm not really sure I'm using the different types of variables correctly, since this are my very first ruby experiences, and I didn't try it till, now. ;-) I'll do that on occasion. ;-)

The code in Pull-Request #21 was in use for more than a year, now. It's working, but of course not looking really nice. ;-)

Kind regards
      Lars

**Comment by LarsKollstedt** [comment]
Hi ytti,

I found the time to try out my idea for consolidated code, and it worked. I cleaned up my changed debug output a bit, and rebased my filter_thoughts into my master. It already got into Pull Request #21 by this.  As far as I can see the functions run_group, run_ostype and run_regex are used nowere else, so I didn't find a reason to keep them, when not used anymore.

Please have a look at the new version of the Pull Request. ;-)

Kind regards,
     Lars

**Comment by LarsKollstedt** [comment]
Hi ytti,
thank you for merging #21. :-)
Kind regards
    Lars
