### ISSUE TITLE
uninitialized class variable @@asetus in Oxidized (NameError)

### ISSUE THREAD

**Issue by alpern95** [ytti/oxidized-script#3]
Hello,
I trye to launch the oxidized-script inside a ruby programe (the example in the Readme.md.
But i have an error : The command line oxs  work well.
 ./test.rb
**/var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized.rb:16:in `asetus': uninitialized class variable @@asetus in Oxidized (NameError)**
        from /var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized.rb:24:in `config'
        from /var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/nodes.rb:12:in`block in load'
        from /var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/nodes.rb:110:in `synchronize'
        from /var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/nodes.rb:110:in`with_lock'
        from /var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/nodes.rb:10:in `load'
        from /var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/nodes.rb:105:in`initialize'
        from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.2/lib/oxidized/script/script.rb:69:in `new'
        from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.2/lib/oxidized/script/script.rb:69:in`initialize'
        from ./test.rb:4:in `new'
        from ./test.rb:4:in`<main>'

My script the same as the readme
more test.rb
# !/usr/bin/env ruby

require 'oxidized/script'

Oxidized::Script.new(:host=>'62.236.123.199') do |oxs|
  puts oxs.cmd 'show mac address-table dynamic vlan 101'
end

ruby -v
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]

Oxidized gem
oxidized (0.12.2)
oxidized-script (0.1.2

cat /etc/os-release
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by ytti** [comment]
Thanks for reporting, this is actually issue #1 incorrectly fixed
