### ISSUE TITLE
Any plan to update slop version of oxidized script

### ISSUE THREAD

**Issue by sajiby3k** [ytti/oxidized-script#39]
Hi,

It has been many moths after oxidized upgrade the slop version has not fixed in oxidized-script.

Can the developer give some love to the oxidized-script and update slop version?

Please!!!

**Comment by ytti** [comment]
My apologies but I'm not currently planning to work on this any time soon, hopefully someone will submit a PR. This is duplicate of #36 so closing.

**Comment by ytti** [comment]
Duplicate of #36
